### ISSUE TITLE
Cython doesn't recognize pymalloc Python

### ISSUE THREAD

**Issue by davidbrochart** [cython/cython#3288]
I have a conda environment which exhibits a bug when using Cython. I was not able to reduce the dependency list without making the bug disappear, so here is the full environment:
```yml
# environment.yml
name: test
channels:
  - conda-forge
  - defaults
dependencies:
  - pip
  - compilers
  - make
  - setuptools
  - cython
  - daetk
  - hdf5 =*=*mpich*
  - h5py =*=*mpich*
  - metis
  - mpich
  - numpy
  - openblas
  - parmetis
  - petsc4py
  - petsc
  - python=3
  - scorec
  - superlu
  - superlu_dist
  - triangle
  - pychrono
  - mpi4py
  - gmsh
  - matplotlib
  - mpi4py
  - nose
  - pytables
  - pytest
  - pytest-cov
  - pytest-xdist
  - scipy
  - tetgen
  - ncurses
  - pychrono
  - python=3
  - future
  - ipyparallel
  - pillow
  - recordtype
```
Create the environment with: `conda env create -f environment.yml`

Activate it: `conda activate test`

Create a file `helloworld.pyx`:
```python
print("Hello World")
```
Create a `setup.py`:
```python
from distutils.core import setup
from Cython.Build import cythonize

setup(
    ext_modules = cythonize("helloworld.pyx")
)
```
Cythonize it: `python setup.py build_ext --inplace`

When you import it with `python -c "import helloworld"`, you get the following error:
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ModuleNotFoundError: No module named 'helloworld'
```
It created a file `helloworld.cpython-37-x86_64-linux-gnu.so`, where it should have been `helloworld.cpython-37m-x86_64-linux-gnu.so`. Indeed you can verify that it works fine if you rename it:
```bash
mv helloworld.cpython-37-x86_64-linux-gnu.so helloworld.cpython-37m-x86_64-linux-gnu.so
```
And in the conda environment the `m` suffix is present: `$CONDA_PREFIX/include/python3.7m`. I know it is related with whether Python was compiled with pymalloc, but I don't understand why Cython doesn't see that it was in this case.
