### ISSUE TITLE
[DOCS] documentation build fails on readthedocs.org

### ISSUE THREAD

**Issue by GalaxySnail** [cython/cython#5253]
context: https://github.com/readthedocs/readthedocs.org/issues/10015

* Build URL (the latest successful build): https://readthedocs.org/projects/cython/builds/19395633/
* Build URL (the first failed build): https://readthedocs.org/projects/cython/builds/19423261/

It seems that the build failed because latexmk failed to build pdf.

**Comment by mattip** [comment]
FWIW, NumPy decided to stop building official PDF docs since it is too much maintenance work.

**Comment by da-woods** [comment]
I didn't even know we built a pdf version. So I wouldn't miss it if we didn't!

**Comment by 0dminnimda** [comment]
pdf and epub are additionally build be default
readthedocs reccommends to add `.readthedocs.yaml` and there all of the build formats can be specified
SEE: https://docs.readthedocs.io/en/stable/config-file/v2.html#formats

**Comment by 0dminnimda** [comment]
for exmple here is configuration for one of my projects:
```
# .readthedocs.yaml
# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the versions of the tools
build:
  os: ubuntu-20.04
  tools:
    python: "3.11"

python:
  install:
    - requirements: requirements.txt
    - method: setuptools  # runs setup.py
      path: .
  system_packages: true

sphinx:
  builder: html
  configuration: docs/conf.py

# Build the docs in additional formats
formats:
  - pdf
```

if need be, i can make a pr for this
